{% set name = "fluidfoam" %}
{% set version = "0.1.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 94ecb41c7f7876b364c42316fb816a95789a36d685d2a4fd69c637c8ca84f1e0

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy >=1.11
    - scipy >=0.17
    - matplotlib >=1.5

test:
  imports:
    - fluidfoam

about:
  home: https://bitbucket.org/fluiddyn/fluidfoam
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE.txt 
  summary: Openfoam PostProcessing Python Tools

extra:
  recipe-maintainers:
    - CyrilleBonamy
