travis:
  secure:
    BINSTAR_TOKEN: kbekoRsRE2mmV2vZ1SWw2l4IO0msB7FfujOksdqRO7VRqkDAxtBlZqeXoZgzegK3I5wbkRSy9DgoKH6PROU+4ZrRRkWR1bVT1SqJcX/Q3OnAuxisyHo3oq3ebc50FEJQQKRjIeJ0mEoDPxNKaOfWwt1gk8/6ihVxDCmTn/nX2VKpQb+xkQpWYOGR8eLU/aQvI9VVZz4b+uwvYRaLuxho6Jk9FQBdZ9OSrQTvVuoY6IZehyXkTlvDgsgDErwdhXHErhXI1rjNshBl8e/KJV/IhVSdMlGKZ72zgjQepOE0uQsnBjYhlGSo7j0dhm1c4uS3pc/AyMtuqctaboOxIyLTjHqLnnBagM/mDOp7/UPkd8dWir+VfcDHBg3OdFrA1Z2mfE24772LQ2ROELvFwqkCEmIYWGxtUVcZqja+PREYZ9foB2pVNsQInjLnmuLQyZm18sprQegLUl50gAty9xukoKwA0ynLP92xZNZonL5PwF78bMnLXvJZcW5m6Ptr2MxuHfCZKPTXMBGxWyCb/hWw/a3rfrl6JWDPecdhMGY9vvVWgq22SbtOIZ+gat+FfhGl0i1K8BVKrPsn6voTCACRkII6mjQojt7DuIxXhoIQhwiknPEaTJJCUnfIatSLhs318zU4v5jDNeovUvKqNrL5RML74MrZjgcbuthFxrrJ8U4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
