travis:
  secure:
    BINSTAR_TOKEN: oiwhEgaIe0gP1Xl2MfCyW+LpOR4xuHVBnstwTaI8yoe+OPkAtxGAeWhmzedkfDHcH2hmIj/qBhl4SQZhWezmWDOAiFz0NtduH1wJTv/rcJIu03cOpMWFb7t0t0tFeH2+TW2e5CZj5dvM2WOvRqGilvn+OcM6EJoTIoVZLUb/1J5e0bSjAOh74E9GAINq/+SwdDTCZEi+pwedKQ67xYZVL+Dco6Yiz2DXyowTHd5mK89DXE9yMgG06LiKC5JssWk9puPoNo+zybSHoY5qVQgA+npiRenBLL4BadNyLPbRnd+96DICyxved/gD1nqjU6hiEWSg96A7zxcwMy+zFgAIBp752BdFSr9aBu/Dd7Wicdo6onexTIG4jQGuI4YDX1FkNOyeKv5II6KvrFCUkA72u7yBPmIwrfteuH4WE5R1tjpjX12MzMHcWdW2e0SvCKvf9qr/DopjvRadHIj/rjCthswDcCywyhZpTPxaparWIk+6O7m7UI4e6AAB9aOAVUQbSi/5nXR3WaHgxF24p79N/SRg3a73HXPcU3n5aLht161WoTeVso8JGtookWI3T9ihHx4CP4T7pk478Qt3Ejyll3tVbu4+L3DTDsK7a3EXFpRgJQDd1h690EowV0TZ+b0uE4A2TzRSME0Az4EYgPTfBd7rOag2qPYRNgrXFHMIMsM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
